version: '3.9'
services:
  code:
    image: codercom/code-server:latest
    user: ${UID:?}:${GID:?}
    environment:
      - DOCKER_USER=${USER:?}
    volumes:
      - type: bind
        source: ${HOME:?}/.config/code-server
        target: /home/coder/.config/code-server
      - type: bind
        source: ${HOME:?}/.local/share/code-server
        target: /home/coder/.local/share/code-server
      - type: bind
        source: ${WORKSPACE:?}
        target: /home/coder/workspace
    ports:
      - target: 8080
        published: ${PORT:?}
