version: '3.9'
services:
  code:
    image: codercom/code-server:latest
    user: ${UID:?}:${GID:?}
    environment:
      - DOCKER_USER=${USER:?}
    volumes:
      - type: bind
        source: ${HOME:?}/.config
        target: /home/coder/.config
      - type: bind
        source: ${WORKSPACE:?}
        target: /home/coder/workspace
    ports:
      - target: 8080
        published: ${PORT:?}
